import Head from "next/head";
import Hero from "../components/Hero";
import Navbar from "../components/Navbar";

export default function Home() {
  return (
    <div>
      <Head>
        <title>UniversalFlow</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://uploads-ssl.webflow.com/61706e8fa79688f7323fd4f2/6175548c4110ad1800467db5_Frame%201402.png"
        />
      </Head>
      <div className="h-screen bg-fixed bg-center bg-cover custom-img-2 z-0">
        <div className="absolute top-0 left-0 right-0 bottom-0 bg-black/40">
          <div className="h-screen bg-fixed bg-center bg-cover custom-img z-1">
            <div>
              <Navbar />
              <Hero />
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
