import React from "react";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import logo from "../assets/logo2.png";

const SignUp = () => {
  return (
    <div>
      <Head>
        <title>UniversalFlow</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://uploads-ssl.webflow.com/61706e8fa79688f7323fd4f2/6175548c4110ad1800467db5_Frame%201402.png"
        />
      </Head>
      <div className="block h-screen flex-col items-center bg-[#000614]">
        <Link href="/">
          <a className="flex items-center justify-center">
            <Image src={logo} alt="Universal Flow Logo" />
          </a>
        </Link>
        <div className="mr-[10vw] mb-[5vh] ml-[10vw] pt-[30px] border-t-2 border-white">
          <h1 className="font-['Syncopate'] text-white flex justify-center text-[25px] leading-normal">
            The only account you will ever need
          </h1>
        </div>
        <div className="w-[40vw] mr-auto mb-[10vh] ml-auto py-[52px] px-[25px] rounded-[20px] bg-transparent shadow-inner shadow-cyan-500/50">
          <form
            id="wf-form-Pre-order-form"
            name="wf-form-Pre-order-form"
            data-name="Pre order form"
            method="get"
            className="flex flex-col justify-start items-center font-['Syncopate'] text-[12px] text-white"
            aria-label="Pre order form"
          >
            <select
              id="Select-Country-2"
              name="Select-Country-2"
              data-name="Select Country 2"
              required=""
              className="h-[6vh] mb-[20px] border-solid border-[1px] border-[#8a8888] bg-transparent opacity-100 text-[#a5a3a3] text-[16px] leading-normal font-medium block w-full py-[8px] px-[12px] align-middle"
            >
              <option value="">Select country</option>
              <option value="Afghanistan">Afghanistan</option>
              <option value="Akrotiri">Akrotiri</option>
              <option value="Akrotiri">Akrotiri</option>
              <option value="Akrotiri">Akrotiri</option>
              <option value="Akrotiri">Akrotiri</option>
              <option value="Akrotiri">Akrotiri</option>
            </select>
            <input
              type="email"
              className="h-[6vh] mb-[20px] border-solid border-[1px] border-[#8a8888] bg-transparent opacity-100 text-[#a5a3a3] text-[16px] leading-normal font-medium block w-full py-[8px] px-[12px] align-middle"
              name="email"
              data-name="Email"
              placeholder="Email address"
              id="email"
              required=""
            ></input>
            <input type="submit" value="Sign Up Now" data-wait="Please wait..." className="w-[50%] h-[5vh] rounded-[10px] bg-[#feb721] text-black leading-normal font-medium"></input>
          </form>
        </div>
      </div>
    </div>
  );
};

export default SignUp;
